source 'https://github.com/CocoaPods/Specs.git'

target 'LAPImageGalleryNode', :exclusive => true do
  pod "LAPImageGalleryNode", :path => "../"
  pod 'AsyncDisplayKit'
  pod 'pop', '~> 1.0'
  pod 'Shimmer', '~> 1.0'
  pod 'AFNetworking', '~> 2.4'
end

target 'Tests', :exclusive => true do
  pod "LAPImageGalleryNode", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
